### ISSUE TITLE
Installation of the 'Encrypt Tiddler'

### ISSUE THREAD

**Issue by mccurcio** [danielo515/TW5-EncryptTiddlerPlugin#10]
Hi Danielo,
I would really like to use your 'Encrypt Tiddler' plugin for Tiddlywiki that allows you to encrypt a single tiddler but I am not sure how to install it properly.

Would it be possible to get better instructions for a newbie like myself.   I have not used Tiddlywikis much but could help write up a part of the wiki page with your help. ;)

Matt C.
matt.curcio.ri@gmail.com

**Comment by danielo515** [comment]
Hello @mccurcio,

The installation is very simple. You just have to visit the demo page an grab the plugin. I will include a reference to the demo on the readme. 

Regards

**Comment by danielo515** [comment]
Here is the page:
https://danielorodriguez.com/TW5-EncryptTiddlerPlugin/

**Comment by danielo515** [comment]
Let me know if installation is not clear. I added the link to the main repo page
