### ISSUE TITLE
Publish internal macros

### ISSUE THREAD

**Issue by AnthonyMuscio** [danielo515/TW5-EncryptTiddlerPlugin#14]
Daniel,
As far as I know your encrypt tiddler plugin is the only tiddler level encrypter.

- It continues to work on the latest version.
- It works well for individual tiddler encryption by an interactive user

However with advances in hosting options I see it could be key to user management in wikis. For example using the decryption key to decrypt a tiddler (Like a login password) that then grants additional functionality. A Form of sign in, and use the same key to re-encrypt on logout. This can also be stored in local browser storage. 

I was wondering if you could document the inner widgets or macros in the EncryptTiddler plugin so that it can be adapted into such solutions rather than just as a button driven solution?

I understand this has being "quiet" for a time.

Thanks
Tony

**Comment by danielo515** [comment]
> This can also be stored in local browser storage.

This is, literally, a bad security practice.
This is very similar to #15 
Could you take a look at the alternatives I proposed there?

About the internals... it is not much. Just a bunch of mechanisms that triggers the already existing tiddlywiki encryption functions on user demand and at a tiddler leve. It does not introduce anything fancy.

**Comment by AnthonyMuscio** [comment]
I will close this and comment in the other thread.
