### ISSUE TITLE
change deault tiddler message

### ISSUE THREAD

**Issue by hchaase** [danielo515/TW5-EncryptTiddlerPlugin#20]
it would be great to be able to change the default tiddler text messeage ("This is an encrypted Tiddler").

you have stated your strategy of not hiding the pad lock in order to be able to hide that the tiddler is encrypted. If the default text instead of "This is an encrypted Tiddler" was something like "under construction" this would look a lot more inconspicuous if someone is snooping in your wiki. and if the default text was a user input field e.g. in the settings this would be very flexible.

I would imaging some text like 

* under construction
* in development
* write this later

what do you think

**Comment by danielo515** [comment]
I like the idea

**Comment by SonephetR2** [comment]
This should be pretty easy to change manually in $:/plugins/danielo515/encryptTiddler/encrypttiddler.js wouldn't it? ("text: "!This is an encrypted Tiddler"). In any case, it would indeed be nice to be able to change that in an upgrade-friendly manner, be it only because the text uses a H1 class instead of a more logical H2 class.

**Comment by danielo515** [comment]
I'll try to implement it this weekend.

**Comment by danielo515** [comment]
I have a pull request ready to add this feature.
Let me know if the preview looks cool for yo:
https://deploy-preview-28--tw5-encrypt-tidler.netlify.app/

**Comment by SonephetR2** [comment]
Thanks a lot @danielo515. It's indeed very easy to modify now. I love how can actually put a fully-fledged tiddler rather than a simple text.

**Comment by danielo515** [comment]
I'm glad you liked it.
For me, using tiddlers as pieces of configuration feels like a TW standard.
I'll merge the MR and it should be up in some minutes.

Regards
