### ISSUE TITLE
Improvement: Tool Icons & Description

### ISSUE THREAD

**Issue by mrmattson** [danielo515/TW5-EncryptTiddlerPlugin#22]
If you add a "caption" and "description" to the "$:/plugins/danielo515/encryptTiddler/crypt-button", the "View Toolbar" (see Screen Shot 1) will be populated with this data under "ControlPanel" (see Screen Shot 2).

Thanks for your consideration!

### Fields:

- caption: {{$:/core/images/locked-padlock}} Encrypt/Decrypt
- description: Encrypt or decrypt this tiddler only

### Screen Shot 1

<img width="712" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/660759/103566231-4596e300-4e87-11eb-89f2-e7f0c013a17b.png">

### Screen Shot 2

<img width="727" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/660759/103566237-4891d380-4e87-11eb-994f-0c3b26ba7109.png">

**Comment by danielo515** [comment]
Thanks for the detailed issue @mrmattson 
Just added the suggested changes. Will be live as soon as it builds
