### ISSUE TITLE
Ask for password confirmation

### ISSUE THREAD

**Issue by danielo515** [danielo515/TW5-EncryptTiddlerPlugin#4]
When encrypting it would be very handy to have a prompt or something asking for password confirmation, because it's very easy to mistype a word. Suggested by Måns at TW forum: https://groups.google.com/d/msg/tiddlywiki/aNGoP1w52qM/MjPAMiz_IskJ

**Comment by digitalap3** [comment]
An easier solution may be to just allow the password to be seen as it is typed.  The convention of hiding the password is a little silly IMO.  If someone is looking over your shoulder they will see you type it anyways.
Thank you for this plugin

**Comment by hchaase** [comment]
I agree with both. I have lost some tiddlers because of typos. Will this issue be adressed?

**Comment by danielo515** [comment]
@hchaase yes, I want to address this as soon as possible. However, I don't have much time these days.

Regards

**Comment by jdubbbb** [comment]
With FF57 soon breaking TiddlyFox (and easy single file saving for TiddlyWiki) which forces me over to unencrypted Node.JS files. This plugin is now essential but it would be too easy to lose a valuable tiddler with a typo. Really hoping this issue can be addressed.

**Comment by danielo515** [comment]
@jdubbbb it should not be hard to implement. Any PR is welcome.
Basically it is as easy as creating two input fields, each one pointing to a temporary state tiddler. Then hide the encrypt button unless the content of both tiddlers is the same.
Any other fancy visual aid will be a plus.
Regards

**Comment by danielo515** [comment]
I merged the PR that should fix this but doesn't look pretty:

![image](https://user-images.githubusercontent.com/2270425/79952349-9641e980-847a-11ea-8451-833aee0f3813.png)

I'll make some cosmetic changes
