### ISSUE TITLE
Filter result should not show non-existing tiddler

### ISSUE THREAD

**Issue by twMat** [danielo515/TW5-EncryptTiddlerPlugin#5]
Assuming the latest version is this one:
http://danielorodriguez.com/TW5-EncryptTiddlerPlugin/

then I propose to make the filter result not show non-existing tiddlers. I.e if I type in foobar, it will show:

*1 matches*
*foobar*

This is a bit confusing.

**Comment by danielo515** [comment]
Hello @twMat,

This is an old tw bug. I'm not sure if it is still present. Every filter operation always return one result, even if that result is a string saying "there are no results"

**Comment by twMat** [comment]
thanx. you're right. It is a (standard) tw issue.
closing.
